import type { ComponentDoc } from './components.data.types';
import {
  FormBasicDemo,
  FormCheckboxDemo,
  FormDatePickerDemo,
  FormDateRangeDemo,
  FormNumberTextareaDemo,
  FormWithValidationDemo,
  FormComboboxDemo,
  FormMultiComboboxDemo,
  FormUploadFileDemo,
} from './components.data.demos';

export const formDocs: ComponentDoc[] = [
  {
    id: 'form-basic',
    title: 'Form (Input + Select)',
    description: 'Minimal form using react-hook-form and provided fields.',
    demo: <FormBasicDemo />,
    imports: "import { FormContainer, FormInput, FormSelect } from '@components/forms';\nimport { useForm } from 'react-hook-form';",
    code: 'const form = useForm();\n<FormContainer formContext={form} onSuccess={console.log}>\n  <FormInput name="email" label="Email" />\n  <FormSelect name="fruit" control={form.control} options={[{id:\'apple\',name:\'Apple\'}]} getOptionLabel={(o)=>o.name} getOptionValue={(o)=>o.id} />\n  <Button type="submit">Submit</Button>\n</FormContainer>',
    tags: ['forms', 'input', 'select'],
  },
  {
    id: 'form-checkbox',
    title: 'FormCheckbox',
    description: 'Controlled checkbox component.',
    demo: <FormCheckboxDemo />,
    imports: "import { FormContainer, FormCheckbox } from '@components/forms';\nimport { useForm } from 'react-hook-form';",
    code: 'const form = useForm();\n<FormContainer formContext={form} onSuccess={console.log}>\n  <FormCheckbox name="agree" control={form.control} label="I agree" />\n</FormContainer>',
    tags: ['forms', 'checkbox'],
  },
  {
    id: 'form-date',
    title: 'FormDatePicker',
    description: 'Single date picker field.',
    demo: <FormDatePickerDemo />,
    imports: "import { FormContainer, FormDatePicker } from '@components/forms';\nimport { useForm } from 'react-hook-form';",
    code: 'const form = useForm();\n<FormContainer formContext={form} onSuccess={console.log}>\n  <FormDatePicker name="date" control={form.control} label="Date" />\n</FormContainer>',
    tags: ['forms', 'date'],
  },
  {
    id: 'form-daterange',
    title: 'FormDateRange',
    description: 'Pick a date range.',
    demo: <FormDateRangeDemo />,
    imports: "import { FormContainer, FormDateRange } from '@components/forms';\nimport { useForm } from 'react-hook-form';",
    code: 'const form = useForm();\n<FormContainer formContext={form} onSuccess={console.log}>\n  <FormDateRange name="range" control={form.control} label="Range" />\n</FormContainer>',
    tags: ['forms', 'date'],
  },
  {
    id: 'form-number-textarea',
    title: 'FormNumber & FormTextarea',
    description: 'Numeric and multi-line text fields.',
    demo: <FormNumberTextareaDemo />,
    imports: "import { FormContainer, FormNumber, FormTextarea } from '@components/forms';\nimport { useForm } from 'react-hook-form';",
    code: 'const form = useForm();\n<FormContainer formContext={form} onSuccess={console.log}>\n  <FormNumber name="qty" control={form.control} label="Quantity" />\n  <FormTextarea name="notes" label="Notes" />\n</FormContainer>',
    tags: ['forms', 'number', 'textarea'],
  },
  {
    id: 'form-validation',
    title: 'Form with Zod Validation',
    description: 'Form with schema validation using Zod.',
    demo: <FormWithValidationDemo />,
    imports:
      "import { FormContainer, FormInput, FormNumber, Button } from '@components/forms';\nimport { useForm } from 'react-hook-form';\nimport { z } from 'zod';",
    code: 'const schema = z.object({\n  email: z.string().email(\'Invalid email\'),\n  password: z.string().min(8, \'Min 8 chars\'),\n  age: z.number().min(18, \'Must be 18+\'),\n});\n\ntype FormData = z.infer<typeof schema>;\n\nconst form = useForm<FormData>({\n  defaultValues: { email: \'\', password: \'\', age: 18 },\n});\n\n<FormContainer formContext={form} onSuccess={console.log}>\n  <FormInput name="email" label="Email" required />\n  <FormInput name="password" type="password" label="Password" required />\n  <FormNumber name="age" control={form.control} label="Age" />\n  <Button type="submit">Submit</Button>\n</FormContainer>',
    tags: ['forms', 'validation', 'zod'],
  },
  {
    id: 'form-combobox',
    title: 'FormCombobox (Searchable Select)',
    description: 'Searchable dropdown with autocomplete.',
    demo: <FormComboboxDemo />,
    imports: "import { FormContainer, FormCombobox } from '@components/forms';\nimport { useForm } from 'react-hook-form';",
    code: "const form = useForm();\nconst options = [\n  { id: 'us', name: 'United States' },\n  { id: 'uk', name: 'United Kingdom' },\n];\n\n<FormContainer formContext={form} onSuccess={console.log}>\n  <FormCombobox\n    name=\"country\"\n    control={form.control}\n    label=\"Country\"\n    options={options}\n    getOptionLabel={(o) => o.name}\n    getOptionValue={(o) => o.id}\n    placeholder=\"Search country...\"\n  />\n</FormContainer>",
    tags: ['forms', 'combobox', 'search'],
  },
  {
    id: 'form-multi-combobox',
    title: 'FormMultiCombobox (Multi-select)',
    description: 'Multiple selection with badges and search.',
    demo: <FormMultiComboboxDemo />,
    imports: "import { FormContainer, FormMultiCombobox } from '@components/forms';\nimport { useForm } from 'react-hook-form';",
    code: "const form = useForm({ defaultValues: { skills: [] } });\nconst skills = [\n  { id: 'js', name: 'JavaScript' },\n  { id: 'ts', name: 'TypeScript' },\n];\n\n<FormContainer formContext={form} onSuccess={console.log}>\n  <FormMultiCombobox\n    name=\"skills\"\n    control={form.control}\n    label=\"Skills\"\n    options={skills}\n    getOptionLabel={(o) => o.name}\n    getOptionValue={(o) => o.id}\n    placeholder=\"Select skills...\"\n  />\n</FormContainer>",
    tags: ['forms', 'multi-select', 'combobox'],
  },
  {
    id: 'form-upload-file',
    title: 'FormUploadFile',
    description: 'File upload with preview and validation.',
    demo: <FormUploadFileDemo />,
    imports: "import { FormContainer, FormUploadFile } from '@components/forms';\nimport { useForm } from 'react-hook-form';",
    code: 'const form = useForm();\n\n<FormContainer formContext={form} onSuccess={console.log}>\n  <FormUploadFile\n    name="document"\n    control={form.control}\n    label="Upload Document"\n    accept=".pdf,.doc,.docx"\n  />\n</FormContainer>',
    tags: ['forms', 'upload', 'file'],
  },
];
